### ISSUE TITLE
Not handling msys correctly

### ISSUE THREAD

**Issue by ktbarrett** [ktbarrett/find_libpython#2]
When running in a msys2 environment with their Python I get:

```
$ find_libpython
Traceback (most recent call last):
  File "/usr/bin/find_libpython", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/find_libpython/__init__.py", line 387, in main
    parser.exit(cli_find_libpython(**vars(ns)))
  File "/usr/lib/python3.8/site-packages/find_libpython/__init__.py", line 349, in cli_find_libpython
    path = find_libpython()
  File "/usr/lib/python3.8/site-packages/find_libpython/__init__.py", line 323, in find_libpython
    for path in finding_libpython():
  File "/usr/lib/python3.8/site-packages/find_libpython/__init__.py", line 132, in uniquifying
    for x in items:
  File "/usr/lib/python3.8/site-packages/find_libpython/__init__.py", line 304, in finding_libpython
    for path in candidate_paths():
  File "/usr/lib/python3.8/site-packages/find_libpython/__init__.py", line 132, in uniquifying
    for x in items:
  File "/usr/lib/python3.8/site-packages/find_libpython/__init__.py", line 202, in candidate_paths
    yield linked_libpython()
  File "/usr/lib/python3.8/site-packages/find_libpython/__init__.py", line 69, in linked_libpython
    return _linked_libpython_unix()
  File "/usr/lib/python3.8/site-packages/find_libpython/__init__.py", line 82, in _linked_libpython_unix
    libdl = ctypes.CDLL(ctypes.util.find_library("dl"))
  File "/usr/lib/python3.8/ctypes/__init__.py", line 373, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: No such file or directory
```

Msys2 is not a unix system, there is no libdl.

```
$ python -c 'import sysconfig; print(sysconfig.get_platform())'
msys-3.1.7-x86_64
```

We should be special-casing msys.

**Comment by ktbarrett** [comment]
Closed by #16.
